service:
  name: slsTest

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  STAGE: ${self:provider.stage}
  DB_CONFIG: ${file(./config/config.js):DB_CONFIG}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  environment:
    STAGE: ${self:provider.stage}
    DB_HOST: ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_HOST}
    DB_USER: ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_USER}
    DB_PASSWORD: ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_PASSWORD}

functions:
  first:
    handler: src/first.hello
  second:
    handler: src/second.hello
    events:
    - http:
        method: get
        path: second
